NUM_TOP_K = 5
PATCH_SIZE = 105
NUM_PATCHES = 5
MODEL_PATH = "models/font365_vgg16.pt"

FONT_LABEL_TO_META = {
    0: {
        "fontName": "iroha29umestdn",
        "fontNameJa": "砧 iroha 29ume StdN",
        "fontNameEn": "iroha-29ume-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "fbi4lox",
    },
    1: {
        "fontName": "taaki",
        "fontNameJa": "TA秋",
        "fontNameEn": "ta-aki",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "jqn7soo",
    },
    2: {
        "fontName": "kaiseitokumin",
        "fontNameJa": "解星 特ミン",
        "fontNameEn": "Kaisei Tokumin",
        "fontWeight": 800,
        "type": "google",
        "adobeId": "",
    },
    3: {
        "fontName": "kaiseiopti",
        "fontNameJa": "解星オプティ",
        "fontNameEn": "Kaisei Opti",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    4: {
        "fontName": "hotkointaikk",
        "fontNameJa": "HOT-白舟古印体教漢",
        "fontNameEn": "hot-kointaikk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "odb4lvj",
    },
    5: {
        "fontName": "abkikori",
        "fontNameJa": "ABキコリ",
        "fontNameEn": "ab-kikori",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "sya2rjf",
    },
    6: {
        "fontName": "iroha27keyakistdn",
        "fontNameJa": "砧 iroha 27keyaki StdN",
        "fontNameEn": "iroha-27keyaki-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "dpz3ofv",
    },
    7: {
        "fontName": "iroha22momistdn",
        "fontNameJa": "砧 iroha 22momi StdN",
        "fontNameEn": "iroha-22momi-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "seb7qag",
    },
    8: {
        "fontName": "abkokorono2",
        "fontNameJa": "ABこころNo2",
        "fontNameEn": "ab-kokoro-no2",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "qgf6wtq",
    },
    9: {
        "fontName": "abkotodamaf",
        "fontNameJa": "AB-ことだまF",
        "fontNameEn": "ab-kotodama-f",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ehb8qee",
    },
    10: {
        "fontName": "kinutamaruminkisostdn",
        "fontNameJa": "砧 丸明Kiso StdN",
        "fontNameEn": "kinuta-maruminkiso-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "kji4yhx",
    },
    11: {
        "fontName": "wanpakurera",
        "fontNameJa": "わんぱくレラ-４",
        "fontNameEn": "wanpaku-rera",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "zcc5ezm",
    },
    12: {
        "fontName": "ablineboardbold",
        "fontNameJa": "AB-ラインボードB",
        "fontNameEn": "ab-lineboard-bold",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "akx2nxz",
    },
    13: {
        "fontName": "abkoki",
        "fontNameJa": "AB Koki",
        "fontNameEn": "ab-koki",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "rrm7dsd",
    },
    14: {
        "fontName": "yujimai",
        "fontNameJa": "Yuji Mai",
        "fontNameEn": "Yuji Mai",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    15: {
        "fontName": "notoserifjp",
        "fontNameJa": "Noto Serif Japanese",
        "fontNameEn": "Noto Serif Japanese",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    16: {
        "fontName": "abmarusan",
        "fontNameJa": "ABまるさん",
        "fontNameEn": "ab-marusan",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "prt1csr",
    },
    17: {
        "fontName": "abhierosregular",
        "fontNameJa": "AB-ヒエロスR",
        "fontNameEn": "ab-hieros-regular",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "lyq0mgx",
    },
    18: {
        "fontName": "capirera",
        "fontNameJa": "キャピレラ-１",
        "fontNameEn": "capirera",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "uqg7jrq",
    },
    19: {
        "fontName": "zenkakugothicnew",
        "fontNameJa": "ZEN角ゴシック",
        "fontNameEn": "Zen Kaku Gothic New",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    20: {
        "fontName": "notoserifjp",
        "fontNameJa": "Noto Serif Japanese",
        "fontNameEn": "Noto Serif Japanese",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    21: {
        "fontName": "tbudminchostd",
        "fontNameJa": "TBUD明朝 Std",
        "fontNameEn": "tbudmincho-std",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "aki0lqt",
    },
    22: {
        "fontName": "uddigikyokashopro",
        "fontNameJa": "UDデジタル教科書体",
        "fontNameEn": "uddigikyokasho-pro",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tja0ucd",
    },
    23: {
        "fontName": "notosansjp",
        "fontNameJa": "Noto Sans Japanese",
        "fontNameEn": "Noto Sans Japanese",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    24: {
        "fontName": "zenkakugothicantique",
        "fontNameJa": "ZEN角ゴシックアンティーク",
        "fontNameEn": "Zen Kaku Gothic Antique",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    25: {
        "fontName": "bokutohruika",
        "fontNameJa": "墨東ルイカ-０７",
        "fontNameEn": "bokutoh-ruika",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "yop5oga",
    },
    26: {
        "fontName": "abdigicomb",
        "fontNameJa": "ABデジコンブ",
        "fontNameEn": "ab-digicomb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "zjb8oed",
    },
    27: {
        "fontName": "vdlgigamaru",
        "fontNameJa": "VDL ギガ丸",
        "fontNameEn": "vdl-gigamaru",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "ees6voi",
    },
    28: {
        "fontName": "ruika",
        "fontNameJa": "ルイカ-０９",
        "fontNameEn": "ruika",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "jwq7pyq",
    },
    29: {
        "fontName": "mplus2",
        "fontNameJa": "Mplus 2",
        "fontNameEn": "M PLUS 2",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    30: {
        "fontName": "newtegomin",
        "fontNameJa": "ニューテゴミン",
        "fontNameEn": "New Tegomin",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    31: {
        "fontName": "iroha26tubakistdn",
        "fontNameJa": "砧 iroha 26tubaki StdN",
        "fontNameEn": "iroha-26tubaki-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "hml3pxm",
    },
    32: {
        "fontName": "tadansyaku",
        "fontNameJa": "TA男爵",
        "fontNameEn": "ta-dansyaku",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ucz3ozj",
    },
    33: {
        "fontName": "notosansjp",
        "fontNameJa": "Noto Sans Japanese",
        "fontNameEn": "Noto Sans Japanese",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    34: {
        "fontName": "hotgekai11kk",
        "fontNameJa": "HOT-ゲーカイ11教漢",
        "fontNameEn": "hot-gekai11kk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "cca7ghy",
    },
    35: {
        "fontName": "hotgyoshokk",
        "fontNameJa": "HOT-白舟行書教漢",
        "fontNameEn": "hot-gyoshokk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "rle4lxe",
    },
    36: {
        "fontName": "poprumcute",
        "fontNameJa": "ポプらむ☆キュート",
        "fontNameEn": "poprumcute",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "dsx5ego",
    },
    37: {
        "fontName": "kaiseidecol",
        "fontNameJa": "解星デコール",
        "fontNameEn": "Kaisei Decol",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    38: {
        "fontName": "iroha32sakurastdn",
        "fontNameJa": "砧 iroha 32sakura StdN",
        "fontNameEn": "iroha-32sakura-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "nsd4bel",
    },
    39: {
        "fontName": "abshoutenmaru",
        "fontNameJa": "AB笑点丸",
        "fontNameEn": "ab-shoutenmaru",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "jos2gbd",
    },
    40: {
        "fontName": "mplus1code",
        "fontNameJa": "Mplus 1 Code",
        "fontNameEn": "M PLUS 1 Code",
        "fontWeight": 100,
        "type": "google",
        "adobeId": "",
    },
    41: {
        "fontName": "abajiminmsyueb",
        "fontNameJa": "味明 Modern 秀/EB",
        "fontNameEn": "abajiminm-syueb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "cqi3den",
    },
    42: {
        "fontName": "notosansjp",
        "fontNameJa": "Noto Sans Japanese",
        "fontNameEn": "Noto Sans Japanese",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    43: {
        "fontName": "notoserifjp",
        "fontNameJa": "Noto Serif Japanese",
        "fontNameEn": "Noto Serif Japanese",
        "fontWeight": 600,
        "type": "google",
        "adobeId": "",
    },
    44: {
        "fontName": "dotgothic16",
        "fontNameJa": "ドットゴシック16",
        "fontNameEn": "DotGothic16",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    45: {
        "fontName": "tayuka",
        "fontNameJa": "TAゆか",
        "fontNameEn": "ta-yuka",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ygo8val",
    },
    46: {
        "fontName": "zenkakugothicantique",
        "fontNameJa": "ZEN角ゴシックアンティーク",
        "fontNameEn": "Zen Kaku Gothic Antique",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    47: {
        "fontName": "mplus1",
        "fontNameJa": "Mplus 1",
        "fontNameEn": "M PLUS 1",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    48: {
        "fontName": "zenmarugothic",
        "fontNameJa": "ZEN丸ゴシック",
        "fontNameEn": "Zen Maru Gothic",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    49: {
        "fontName": "zenkakugothicantique",
        "fontNameJa": "ZEN角ゴシックアンティーク",
        "fontNameEn": "Zen Kaku Gothic Antique",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    50: {
        "fontName": "kaiseiopti",
        "fontNameJa": "解星オプティ",
        "fontNameEn": "Kaisei Opti",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    51: {
        "fontName": "mplus1code",
        "fontNameJa": "Mplus 1 Code",
        "fontNameEn": "M PLUS 1 Code",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    52: {
        "fontName": "vdlpenletter",
        "fontNameJa": "VDL ペンレター",
        "fontNameEn": "vdl-penletter",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "xvx7fdl",
    },
    53: {
        "fontName": "hotkaishokk",
        "fontNameJa": "HOT-白舟楷書教漢",
        "fontNameEn": "hot-kaishokk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "grd0jat",
    },
    54: {
        "fontName": "hotgfkaishokk",
        "fontNameJa": "HOT-白舟極太楷書教漢",
        "fontNameEn": "hot-gfkaishokk",
        "fontWeight": 800,
        "type": "adobe",
        "adobeId": "vjf5vtw",
    },
    55: {
        "fontName": "yamamotoanstdn",
        "fontNameJa": "砧 山本庵 StdN",
        "fontNameEn": "yamamotoan-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "lrl1nrr",
    },
    56: {
        "fontName": "dnpshueiantistd",
        "fontNameJa": "DNP 秀英アンチック Std",
        "fontNameEn": "dnp-shuei-anti-std",
        "fontWeight": 600,
        "type": "adobe",
        "adobeId": "zvj8tok",
    },
    57: {
        "fontName": "mplus1code",
        "fontNameJa": "Mplus 1 Code",
        "fontNameEn": "M PLUS 1 Code",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    58: {
        "fontName": "fotrodinpron",
        "fontNameJa": "FOT-ロダン ProN",
        "fontNameEn": "fot-rodin-pron",
        "fontWeight": 600,
        "type": "adobe",
        "adobeId": "aoo0rrq",
    },
    59: {
        "fontName": "abkotodamau",
        "fontNameJa": "ABことだまU",
        "fontNameEn": "ab-kotodama-u",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mdw0igt",
    },
    60: {
        "fontName": "zenkakugothicantique",
        "fontNameJa": "ZEN角ゴシックアンティーク",
        "fontNameEn": "Zen Kaku Gothic Antique",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    61: {
        "fontName": "mplus2",
        "fontNameJa": "Mplus 2",
        "fontNameEn": "M PLUS 2",
        "fontWeight": 100,
        "type": "google",
        "adobeId": "",
    },
    62: {
        "fontName": "abhasemomor",
        "fontNameJa": "AB長谷桃R",
        "fontNameEn": "ab-hasemomo-r",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "exj7gle",
    },
    63: {
        "fontName": "fotseuratpron",
        "fontNameJa": "FOT-スーラ ProN",
        "fontNameEn": "fot-seurat-pron",
        "fontWeight": 600,
        "type": "adobe",
        "adobeId": "wvg0tmg",
    },
    64: {
        "fontName": "mplus1code",
        "fontNameJa": "Mplus 1 Code",
        "fontNameEn": "M PLUS 1 Code",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    65: {
        "fontName": "abmegadot9",
        "fontNameJa": "AB Megadot9",
        "fontNameEn": "ab-megadot9",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "xrr7vyp",
    },
    66: {
        "fontName": "dnpshuei4gobstd",
        "fontNameJa": "DNP 秀英四号太かな Std",
        "fontNameEn": "dnp-shuei-4gob-std",
        "fontWeight": 700,
        "type": "adobe",
        "adobeId": "kof4xec",
    },
    67: {
        "fontName": "abhanamaki",
        "fontNameJa": "AB Hanamaki",
        "fontNameEn": "ab-hanamaki",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "yks4svp",
    },
    68: {
        "fontName": "vdlmegag",
        "fontNameJa": "VDL メガＧ",
        "fontNameEn": "vdl-megag",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "nav8gms",
    },
    69: {
        "fontName": "absekka",
        "fontNameJa": "AB雪華",
        "fontNameEn": "ab-sekka",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "nak1ndu",
    },
    70: {
        "fontName": "mplus1",
        "fontNameJa": "Mplus 1",
        "fontNameEn": "M PLUS 1",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    71: {
        "fontName": "abtombobold",
        "fontNameJa": "AB Tombo Bold",
        "fontNameEn": "ab-tombo-bold",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "iaw1rxs",
    },
    72: {
        "fontName": "kinutamarumintikumastdn",
        "fontNameJa": "砧 丸明Tikuma StdN",
        "fontNameEn": "kinuta-marumintikuma-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bmm7vek",
    },
    73: {
        "fontName": "toppanbunkyuminchopr6n",
        "fontNameJa": "凸版文久明朝 Pr6N",
        "fontNameEn": "toppan-bunkyu-mincho-pr6n",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "qlf3shh",
    },
    74: {
        "fontName": "tbudrgothicstd",
        "fontNameJa": "TBUD丸ゴシック Std",
        "fontNameEn": "tbudrgothic-std",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "plg7rvd",
    },
    75: {
        "fontName": "kaiseiharunoumi",
        "fontNameJa": "解星 春の海",
        "fontNameEn": "Kaisei HarunoUmi",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    76: {
        "fontName": "abintore",
        "fontNameJa": "ABイントレ",
        "fontNameEn": "ab-intore",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "vax3fal",
    },
    77: {
        "fontName": "shipporimincho",
        "fontNameJa": "しっぽり明朝",
        "fontNameEn": "Shippori Mincho",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    78: {
        "fontName": "oshidashimgothic",
        "fontNameJa": "押出Mゴシック",
        "fontNameEn": "oshidashi-m-gothic",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "fpc5act",
    },
    79: {
        "fontName": "vdlpetag",
        "fontNameJa": "VDL ペタＧ",
        "fontNameEn": "vdl-petag",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "lbq2crk",
    },
    80: {
        "fontName": "abajiminmchikueb",
        "fontNameJa": "味明 Modern 築/EB",
        "fontNameEn": "abajiminm-chikueb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "aby3bnl",
    },
    81: {
        "fontName": "fotudkakugoc60pro",
        "fontNameJa": "FOT-UD角ゴC60 Pro",
        "fontNameEn": "fot-udkakugoc60-pro",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "bky6mlr",
    },
    82: {
        "fontName": "vdllinegr",
        "fontNameJa": "VDL ラインＧアール",
        "fontNameEn": "vdl-linegr",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ltg7owl",
    },
    83: {
        "fontName": "tamiyabi",
        "fontNameJa": "TA-雅",
        "fontNameEn": "ta-miyabi",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bob3xzu",
    },
    84: {
        "fontName": "abyoshienoryokandb",
        "fontNameJa": "AB好恵の良寛さんDB",
        "fontNameEn": "ab-yoshienoryokan-db",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "sjv5azm",
    },
    85: {
        "fontName": "yomogi",
        "fontNameJa": "Yomogi",
        "fontNameEn": "Yomogi",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    86: {
        "fontName": "abtoria",
        "fontNameJa": "AB Tori A",
        "fontNameEn": "ab-tori-a",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "kog5rho",
    },
    87: {
        "fontName": "fottsukuminpr6n",
        "fontNameJa": "FOT-筑紫明朝 Pr6N",
        "fontNameEn": "fot-tsukumin-pr6n",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "tgw0try",
    },
    88: {
        "fontName": "vdlpengentle",
        "fontNameJa": "VDL ペンジェントル",
        "fontNameEn": "vdl-pengentle",
        "fontWeight": 700,
        "type": "adobe",
        "adobeId": "jjc6tvd",
    },
    89: {
        "fontName": "kiwimaru",
        "fontNameJa": "キウイ丸",
        "fontNameEn": "Kiwi Maru",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    90: {
        "fontName": "abpochi",
        "fontNameJa": "AB Pochi",
        "fontNameEn": "ab-pochi",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "rxl5tyk",
    },
    91: {
        "fontName": "yuseimagic",
        "fontNameJa": "YuseiMagic",
        "fontNameEn": "Yusei Magic",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    92: {
        "fontName": "notoserifjp",
        "fontNameJa": "Noto Serif Japanese",
        "fontNameEn": "Noto Serif Japanese",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    93: {
        "fontName": "abhasefude",
        "fontNameJa": "ABはせ筆",
        "fontNameEn": "ab-hasefude",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "doa3jbh",
    },
    94: {
        "fontName": "aotfjunpro",
        "fontNameJa": "A-OTF じゅん Pro",
        "fontNameEn": "a-otf-jun-pro",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "piq8klb",
    },
    95: {
        "fontName": "murecho",
        "fontNameJa": "Murecho",
        "fontNameEn": "Murecho",
        "fontWeight": 200,
        "type": "google",
        "adobeId": "",
    },
    96: {
        "fontName": "reggaeone",
        "fontNameJa": "レゲエ One",
        "fontNameEn": "Reggae One",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    97: {
        "fontName": "kinutamaruminkaturastdn",
        "fontNameJa": "砧 丸明Katura StdN",
        "fontNameEn": "kinuta-maruminkatura-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mom6vla",
    },
    98: {
        "fontName": "zenkakugothicnew",
        "fontNameJa": "ZEN角ゴシック",
        "fontNameEn": "Zen Kaku Gothic New",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    99: {
        "fontName": "vdlmegamaru",
        "fontNameJa": "VDL メガ丸",
        "fontNameEn": "vdl-megamaru",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "pzm0ovq",
    },
    100: {
        "fontName": "tayugemeijin",
        "fontNameJa": "TA Yugemeijin",
        "fontNameEn": "ta-yugemeijin",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mdg5luu",
    },
    101: {
        "fontName": "abtorib",
        "fontNameJa": "AB ToriB",
        "fontNameEn": "ab-tori-b",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "xnb5dhy",
    },
    102: {
        "fontName": "mplus2",
        "fontNameJa": "Mplus 2",
        "fontNameEn": "M PLUS 2",
        "fontWeight": 800,
        "type": "google",
        "adobeId": "",
    },
    103: {
        "fontName": "vdlterag",
        "fontNameJa": "VDL テラＧ",
        "fontNameEn": "vdl-terag",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "bic7shx",
    },
    104: {
        "fontName": "mochiypopone",
        "fontNameJa": "モッチーポップ One",
        "fontNameEn": "Mochiy Pop One",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    105: {
        "fontName": "vdllogomaru",
        "fontNameJa": "VDL ロゴ丸",
        "fontNameEn": "vdl-logomaru",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "jrd0bhz",
    },
    106: {
        "fontName": "abwalk",
        "fontNameJa": "AB-ウォーク",
        "fontNameEn": "ab-walk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bdz1xhb",
    },
    107: {
        "fontName": "mplus1",
        "fontNameJa": "Mplus 1",
        "fontNameEn": "M PLUS 1",
        "fontWeight": 900,
        "type": "google",
        "adobeId": "",
    },
    108: {
        "fontName": "bokutohrera",
        "fontNameJa": "墨東レラ-５",
        "fontNameEn": "bokutoh-rera",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "apd4upi",
    },
    109: {
        "fontName": "aotfryuminpr6n",
        "fontNameJa": "A-OTF リュウミン Pr6N",
        "fontNameEn": "a-otf-ryumin-pr6n",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "csr3vpu",
    },
    110: {
        "fontName": "tasouiimei",
        "fontNameJa": "TA相依為命",
        "fontNameEn": "ta-souiimei",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "xnp0wqo",
    },
    111: {
        "fontName": "abajiminsyuleb",
        "fontNameJa": "味明 秀L/EB",
        "fontNameEn": "abajimin-syuleb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "yjx6whx",
    },
    112: {
        "fontName": "honokaantiquemaru",
        "fontNameJa": "ほのかアンティーク丸",
        "fontNameEn": "honoka-antique-maru",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tcw0qzr",
    },
    113: {
        "fontName": "rampartone",
        "fontNameJa": "ランパート One",
        "fontNameEn": "Rampart One",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    114: {
        "fontName": "abomusubi",
        "fontNameJa": "ABおむすび",
        "fontNameEn": "ab-omusubi",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "hky2nnp",
    },
    115: {
        "fontName": "mitimasu",
        "fontNameJa": "みちます",
        "fontNameEn": "mitimasu",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "zec7mhx",
    },
    116: {
        "fontName": "abanzu",
        "fontNameJa": "AB-杏",
        "fontNameEn": "ab-anzu",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bck3sgy",
    },
    117: {
        "fontName": "fotmatissepron",
        "fontNameJa": "FOT-マティス ProN",
        "fontNameEn": "fot-matisse-pron",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "tri1ept",
    },
    118: {
        "fontName": "septembern",
        "fontNameJa": "セプテンバーＮ３",
        "fontNameEn": "september-n",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "wff2lbj",
    },
    119: {
        "fontName": "tanasubi",
        "fontNameJa": "TA-なすび",
        "fontNameEn": "ta-nasubi",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tpn0bny",
    },
    120: {
        "fontName": "mplus2",
        "fontNameJa": "Mplus 2",
        "fontNameEn": "M PLUS 2",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    121: {
        "fontName": "tapoptomo",
        "fontNameJa": "TA-POP友",
        "fontNameEn": "ta-pop-tomo",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "oab7vut",
    },
    122: {
        "fontName": "kiwimaru",
        "fontNameJa": "キウイ丸",
        "fontNameEn": "Kiwi Maru",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    123: {
        "fontName": "vdllogojrblack",
        "fontNameJa": "VDL ロゴJrブラック",
        "fontNameEn": "vdl-logojrblack",
        "fontWeight": 900,
        "type": "adobe",
        "adobeId": "sgn4zlj",
    },
    124: {
        "fontName": "timemachinewa",
        "fontNameJa": "タイムマシンわ号",
        "fontNameEn": "timemachine-wa",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "vok7upn",
    },
    125: {
        "fontName": "abstickmedium",
        "fontNameJa": "AB-スティックM",
        "fontNameEn": "ab-stick-medium",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ojm6tad",
    },
    126: {
        "fontName": "iroha28kiristdn",
        "fontNameJa": "砧 iroha 28kiri StdN",
        "fontNameEn": "iroha-28kiri-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "oji4jhu",
    },
    127: {
        "fontName": "vdladmin",
        "fontNameJa": "VDL アドミーン",
        "fontNameEn": "vdl-admin",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "syt5sjo",
    },
    128: {
        "fontName": "notosansjp",
        "fontNameJa": "Noto Sans Japanese",
        "fontNameEn": "Noto Sans Japanese",
        "fontWeight": 100,
        "type": "google",
        "adobeId": "",
    },
    129: {
        "fontName": "iroha25ichostdn",
        "fontNameJa": "砧 iroha 25icho StdN",
        "fontNameEn": "iroha-25icho-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "fce4uce",
    },
    130: {
        "fontName": "notoserifjp",
        "fontNameJa": "Noto Serif Japanese",
        "fontNameEn": "Noto Serif Japanese",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    131: {
        "fontName": "kaiseidecol",
        "fontNameJa": "解星デコール",
        "fontNameEn": "Kaisei Decol",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    132: {
        "fontName": "abmaruhanamaki",
        "fontNameJa": "AB-丸花巻",
        "fontNameEn": "ab-maruhanamaki",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "vwr4ols",
    },
    133: {
        "fontName": "kaiseitokumin",
        "fontNameJa": "解星 特ミン",
        "fontNameEn": "Kaisei Tokumin",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    134: {
        "fontName": "vdllogojr",
        "fontNameJa": "VDL ロゴJr",
        "fontNameEn": "vdl-logojr",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "vrc7bjn",
    },
    135: {
        "fontName": "abitaikoku",
        "fontNameJa": "AB一大國",
        "fontNameEn": "ab-itaikoku",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "yph8rkg",
    },
    136: {
        "fontName": "abajiminmmineb",
        "fontNameJa": "味明 Modern 民/EB",
        "fontNameEn": "abajiminm-mineb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "wxy7gqv",
    },
    137: {
        "fontName": "abanzur",
        "fontNameJa": "AB Anzu R",
        "fontNameEn": "ab-anzu-r",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "nyi3ocr",
    },
    138: {
        "fontName": "abappare",
        "fontNameJa": "AB あっぱれ",
        "fontNameEn": "ab-appare",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "til2nqp",
    },
    139: {
        "fontName": "dnpshueinshogominchostd",
        "fontNameJa": "DNP 秀英にじみ初号明朝 Std",
        "fontNameEn": "dnp-shuei-nshogomincho-std",
        "fontWeight": 700,
        "type": "adobe",
        "adobeId": "yvn5kop",
    },
    140: {
        "fontName": "isemin",
        "fontNameJa": "異世明",
        "fontNameEn": "isemin",
        "fontWeight": 900,
        "type": "adobe",
        "adobeId": "jjz2scv",
    },
    141: {
        "fontName": "tamadam",
        "fontNameJa": "TAマダム",
        "fontNameEn": "ta-madam",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mei8kyi",
    },
    142: {
        "fontName": "fotcezannepron",
        "fontNameJa": "FOT-セザンヌ ProN",
        "fontNameEn": "fot-cezanne-pron",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "xun2vjz",
    },
    143: {
        "fontName": "fotudkakugoc70pro",
        "fontNameJa": "FOT-UD角ゴC70 Pro",
        "fontNameEn": "fot-udkakugoc70-pro",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tqn3puf",
    },
    144: {
        "fontName": "tacandy",
        "fontNameJa": "TA-candy",
        "fontNameEn": "ta-candy",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "siq8pyw",
    },
    145: {
        "fontName": "mplus2",
        "fontNameJa": "Mplus 2",
        "fontNameEn": "M PLUS 2",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    146: {
        "fontName": "kaiseitokumin",
        "fontNameJa": "解星 特ミン",
        "fontNameEn": "Kaisei Tokumin",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    147: {
        "fontName": "abkotodamal",
        "fontNameJa": "AB-ことだまL",
        "fontNameEn": "ab-kotodama-l",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "kvf6eho",
    },
    148: {
        "fontName": "abshinyubipenjigyosyotai",
        "fontNameJa": "AB 新優美ペン字行書",
        "fontNameEn": "ab-shinyubipenjigyosyotai",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tii3upk",
    },
    149: {
        "fontName": "zenmarugothic",
        "fontNameJa": "ZEN丸ゴシック",
        "fontNameEn": "Zen Maru Gothic",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    150: {
        "fontName": "abbooing",
        "fontNameJa": "ABブーイング",
        "fontNameEn": "ab-booing",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mzs5lus",
    },
    151: {
        "fontName": "kaiseiharunoumi",
        "fontNameJa": "解星 春の海",
        "fontNameEn": "Kaisei HarunoUmi",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    152: {
        "fontName": "mplus2",
        "fontNameJa": "Mplus 2",
        "fontNameEn": "M PLUS 2",
        "fontWeight": 600,
        "type": "google",
        "adobeId": "",
    },
    153: {
        "fontName": "abkotatsu",
        "fontNameJa": "TA-こたつ",
        "fontNameEn": "ab-kotatsu",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "usp6kvs",
    },
    154: {
        "fontName": "vdlgigag",
        "fontNameJa": "VDL ギガＧ",
        "fontNameEn": "vdl-gigag",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "nen5bbu",
    },
    155: {
        "fontName": "pottaone",
        "fontNameJa": "ポッタ",
        "fontNameEn": "Potta One",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    156: {
        "fontName": "takouran",
        "fontNameJa": "TA香蘭",
        "fontNameEn": "ta-kouran",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tmx3vqg",
    },
    157: {
        "fontName": "abquadra",
        "fontNameJa": "ABクワドラ",
        "fontNameEn": "ab-quadra",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "xdw3umi",
    },
    158: {
        "fontName": "takakushadow",
        "fontNameJa": "TA角シャドー",
        "fontNameEn": "ta-kaku-shadow",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ytn6jal",
    },
    159: {
        "fontName": "notosansjp",
        "fontNameJa": "Noto Sans Japanese",
        "fontNameEn": "Noto Sans Japanese",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    160: {
        "fontName": "abajiminmchikuceb",
        "fontNameJa": "味明 Modern 築Ｃ/EB",
        "fontNameEn": "abajiminm-chikuceb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "zqm6utc",
    },
    161: {
        "fontName": "heiseiminchostdn",
        "fontNameJa": "平成明朝 StdN",
        "fontNameEn": "heisei-mincho-stdn",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "ixv2gpp",
    },
    162: {
        "fontName": "stick",
        "fontNameJa": "ステッキ",
        "fontNameEn": "Stick",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    163: {
        "fontName": "iroha24matustdn",
        "fontNameJa": "砧 iroha 24matu StdN",
        "fontNameEn": "iroha-24matu-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "vbw8mtg",
    },
    164: {
        "fontName": "tafugafude",
        "fontNameJa": "TA風雅筆",
        "fontNameEn": "ta-fuga-fude",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "zyz3qwg",
    },
    165: {
        "fontName": "murecho",
        "fontNameJa": "Murecho",
        "fontNameEn": "Murecho",
        "fontWeight": 800,
        "type": "google",
        "adobeId": "",
    },
    166: {
        "fontName": "abajiminmsyuveb",
        "fontNameJa": "味明 Modern 秀Ｖ/EB",
        "fontNameEn": "abajiminm-syuveb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "jze4sdd",
    },
    167: {
        "fontName": "zenkakugothicnew",
        "fontNameJa": "ZEN角ゴシック",
        "fontNameEn": "Zen Kaku Gothic New",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    168: {
        "fontName": "kazurakisp2n",
        "fontNameJa": "かづらき SP2N",
        "fontNameEn": "kazuraki-sp2n",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "oan1frs",
    },
    169: {
        "fontName": "dnpshuei4gostd",
        "fontNameJa": "DNP 秀英四号かな Std",
        "fontNameEn": "dnp-shuei-4go-std",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "sbv0wuh",
    },
    170: {
        "fontName": "abajiminryoeb",
        "fontNameJa": "味明 良/EB",
        "fontNameEn": "abajimin-ryoeb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "drw1gql",
    },
    171: {
        "fontName": "abfudeshichi",
        "fontNameJa": "AB-筆七",
        "fontNameEn": "ab-fudeshichi",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "jic1fih",
    },
    172: {
        "fontName": "abkokorono1",
        "fontNameJa": "AB-こころNo.1",
        "fontNameEn": "ab-kokoro-no1",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mom3knf",
    },
    173: {
        "fontName": "hinamincho",
        "fontNameJa": "ひな明朝",
        "fontNameEn": "Hina Mincho",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    174: {
        "fontName": "murecho",
        "fontNameJa": "Murecho",
        "fontNameEn": "Murecho",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    175: {
        "fontName": "abajiminkoheb",
        "fontNameJa": "味明 弘/EB",
        "fontNameEn": "abajimin-koheb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "sea3oew",
    },
    176: {
        "fontName": "abclipmedium",
        "fontNameJa": "AB-くりっぷM",
        "fontNameEn": "ab-clip-medium",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "dxk2qcw",
    },
    177: {
        "fontName": "mplus1",
        "fontNameJa": "Mplus 1",
        "fontNameEn": "M PLUS 1",
        "fontWeight": 800,
        "type": "google",
        "adobeId": "",
    },
    178: {
        "fontName": "abryushichi",
        "fontNameJa": "AB Ryushichi",
        "fontNameEn": "ab-ryushichi",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "wbf1ned",
    },
    179: {
        "fontName": "absurugau",
        "fontNameJa": "AB-駿河U",
        "fontNameEn": "ab-suruga-u",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ifp1uiz",
    },
    180: {
        "fontName": "takotodamar",
        "fontNameJa": "TA-ことだまR",
        "fontNameEn": "ta-kotodama-r",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tqr6uux",
    },
    181: {
        "fontName": "abaotama",
        "fontNameJa": "AB Aotama",
        "fontNameEn": "ab-aotama",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "lei4oqm",
    },
    182: {
        "fontName": "takobe",
        "fontNameJa": "TA-神戸",
        "fontNameEn": "ta-kobe",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "keu7aod",
    },
    183: {
        "fontName": "zenoldmincho",
        "fontNameJa": "ZENオールド明朝",
        "fontNameEn": "Zen Old Mincho",
        "fontWeight": 900,
        "type": "google",
        "adobeId": "",
    },
    184: {
        "fontName": "takoigokoro",
        "fontNameJa": "TA恋心",
        "fontNameEn": "ta-koigokoro",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "riv4cvg",
    },
    185: {
        "fontName": "vdlyotag",
        "fontNameJa": "VDL ヨタＧ",
        "fontNameEn": "vdl-yotag",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "onw3zqc",
    },
    186: {
        "fontName": "abajimingyoeb",
        "fontNameJa": "味明 行/EB",
        "fontNameEn": "abajimin-gyoeb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "iks3ytd",
    },
    187: {
        "fontName": "delagothicone",
        "fontNameJa": "デラゴシック",
        "fontNameEn": "Dela Gothic One",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    188: {
        "fontName": "kleeone",
        "fontNameJa": "クレー One",
        "fontNameEn": "Klee One",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    189: {
        "fontName": "aotfudshingocon80pr6n",
        "fontNameJa": "A-OTF UD新ゴコンデ80 Pr6N",
        "fontNameEn": "a-otf-ud-shin-go-con80-pr6n",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "jkl4qld",
    },
    190: {
        "fontName": "yujiboku",
        "fontNameJa": "Yuji Boku",
        "fontNameEn": "Yuji Boku",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    191: {
        "fontName": "kokuryu",
        "fontNameJa": "黒龍爽",
        "fontNameEn": "kokuryu",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bce7ztw",
    },
    192: {
        "fontName": "abbabywalk",
        "fontNameJa": "ABベイビーウォーク",
        "fontNameEn": "ab-babywalk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "lgs7hge",
    },
    193: {
        "fontName": "kaiseitokumin",
        "fontNameJa": "解星 特ミン",
        "fontNameEn": "Kaisei Tokumin",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    194: {
        "fontName": "abyurumin",
        "fontNameJa": "AB-ゆるみん",
        "fontNameEn": "ab-yurumin",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "wik6ixi",
    },
    195: {
        "fontName": "genkaimincho",
        "fontNameJa": "源界明朝",
        "fontNameEn": "genkaimincho",
        "fontWeight": 800,
        "type": "adobe",
        "adobeId": "puf6tlr",
    },
    196: {
        "fontName": "taoonishi",
        "fontNameJa": "TA-おおにし",
        "fontNameEn": "ta-oonishi",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "opt4hby",
    },
    197: {
        "fontName": "wanpakuruika",
        "fontNameJa": "わんぱくルイカ-０８",
        "fontNameEn": "wanpaku-ruika",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "hzz0nbj",
    },
    198: {
        "fontName": "abajiminsoeb",
        "fontNameJa": "味明 草/EB",
        "fontNameEn": "abajimin-soeb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "prs1unw",
    },
    199: {
        "fontName": "zenmarugothic",
        "fontNameJa": "ZEN丸ゴシック",
        "fontNameEn": "Zen Maru Gothic",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    200: {
        "fontName": "tapopkaku",
        "fontNameJa": "TA-ポップ角",
        "fontNameEn": "ta-pop-kaku",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "jlu7cyn",
    },
    201: {
        "fontName": "shipporimincho",
        "fontNameJa": "しっぽり明朝",
        "fontNameEn": "Shippori Mincho",
        "fontWeight": 600,
        "type": "google",
        "adobeId": "",
    },
    202: {
        "fontName": "vdllogog",
        "fontNameJa": "VDL ロゴG",
        "fontNameEn": "vdl-logog",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "gzw1qnv",
    },
    203: {
        "fontName": "abdoudoukaisyo",
        "fontNameJa": "AB-堂々楷書",
        "fontNameEn": "ab-doudoukaisyo",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "fta5jps",
    },
    204: {
        "fontName": "hotsoshokk",
        "fontNameJa": "HOT-白舟草書教漢",
        "fontNameEn": "hot-soshokk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "xsg2hxu",
    },
    205: {
        "fontName": "mplus1code",
        "fontNameJa": "Mplus 1 Code",
        "fontNameEn": "M PLUS 1 Code",
        "fontWeight": 600,
        "type": "google",
        "adobeId": "",
    },
    206: {
        "fontName": "mplus2",
        "fontNameJa": "Mplus 2",
        "fontNameEn": "M PLUS 2",
        "fontWeight": 900,
        "type": "google",
        "adobeId": "",
    },
    207: {
        "fontName": "vdlgothicmincho",
        "fontNameJa": "VDL G明朝",
        "fontNameEn": "vdl-gothicmincho",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ehc5iuf",
    },
    208: {
        "fontName": "zenantique",
        "fontNameJa": "ZENアンティーク",
        "fontNameEn": "Zen Antique",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    209: {
        "fontName": "tahougank500",
        "fontNameJa": "TA-方眼K500",
        "fontNameEn": "ta-hougan-k500",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "dcj4wad",
    },
    210: {
        "fontName": "iroha30momijistdn",
        "fontNameJa": "砧 iroha 30momiji StdN",
        "fontNameEn": "iroha-30momiji-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "dnl7gyn",
    },
    211: {
        "fontName": "abdonmai",
        "fontNameJa": "ABドンマイ",
        "fontNameEn": "ab-donmai",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "hjp7gyw",
    },
    212: {
        "fontName": "zenmarugothic",
        "fontNameJa": "ZEN丸ゴシック",
        "fontNameEn": "Zen Maru Gothic",
        "fontWeight": 900,
        "type": "google",
        "adobeId": "",
    },
    213: {
        "fontName": "nitalagoruika",
        "fontNameJa": "ニタラゴルイカ-０６",
        "fontNameEn": "nitalago-ruika",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "gir5urb",
    },
    214: {
        "fontName": "aotfudreiminpr6n",
        "fontNameJa": "A-OTF UD黎ミン Pr6N",
        "fontNameEn": "a-otf-ud-reimin-pr6n",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "bqu5lpg",
    },
    215: {
        "fontName": "kaiseiopti",
        "fontNameJa": "解星オプティ",
        "fontNameEn": "Kaisei Opti",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    216: {
        "fontName": "abnara",
        "fontNameJa": "AB奈良",
        "fontNameEn": "ab-nara",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "iuf8orf",
    },
    217: {
        "fontName": "abandante",
        "fontNameJa": "AB-アンダンテ",
        "fontNameEn": "ab-andante",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "uor0emn",
    },
    218: {
        "fontName": "vdllogomarujr",
        "fontNameJa": "VDL ロゴ丸Jr",
        "fontNameEn": "vdl-logomaru-jr",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "vdg8hpa",
    },
    219: {
        "fontName": "abajiminsyueb",
        "fontNameJa": "味明 秀/EB",
        "fontNameEn": "abajimin-syueb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "xom3vhc",
    },
    220: {
        "fontName": "absuzume",
        "fontNameJa": "ABすずめ",
        "fontNameEn": "ab-suzume",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "kib5qxw",
    },
    221: {
        "fontName": "kinutamaruminyoshinostdn",
        "fontNameJa": "砧 丸明Yoshino StdN",
        "fontNameEn": "kinuta-maruminyoshino-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "gtn3wez",
    },
    222: {
        "fontName": "abkirakul",
        "fontNameJa": "AB喜楽L",
        "fontNameEn": "ab-kiraku-l",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "fwr0lcn",
    },
    223: {
        "fontName": "ab24h",
        "fontNameJa": "AB 24h",
        "fontNameEn": "ab-24h",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bat1swp",
    },
    224: {
        "fontName": "abtegami",
        "fontNameJa": "AB-手紙",
        "fontNameEn": "ab-tegami",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "qrj3pnm",
    },
    225: {
        "fontName": "zenmarugothic",
        "fontNameJa": "ZEN丸ゴシック",
        "fontNameEn": "Zen Maru Gothic",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    226: {
        "fontName": "murecho",
        "fontNameJa": "Murecho",
        "fontNameEn": "Murecho",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    227: {
        "fontName": "kosugi",
        "fontNameJa": "小杉フォント",
        "fontNameEn": "Kosugi",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    228: {
        "fontName": "hottenkoinkk",
        "fontNameJa": "HOT-白舟篆古印教漢",
        "fontNameEn": "hot-tenkoinkk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "wkz8hww",
    },
    229: {
        "fontName": "abkinmokuseikuro",
        "fontNameJa": "AB Kinmokusei Kuro",
        "fontNameEn": "ab-kinmokusei-kuro",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ved8ntb",
    },
    230: {
        "fontName": "mplus1",
        "fontNameJa": "Mplus 1",
        "fontNameEn": "M PLUS 1",
        "fontWeight": 100,
        "type": "google",
        "adobeId": "",
    },
    231: {
        "fontName": "isego",
        "fontNameJa": "異世ゴ",
        "fontNameEn": "isego",
        "fontWeight": 700,
        "type": "adobe",
        "adobeId": "arc6loi",
    },
    232: {
        "fontName": "tahoudatem500",
        "fontNameJa": "TA-方縦M500",
        "fontNameEn": "ta-houdate-m500",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "vpg6meq",
    },
    233: {
        "fontName": "fotchiarostd",
        "fontNameJa": "FOT-キアロ Std",
        "fontNameEn": "fot-chiaro-std",
        "fontWeight": 700,
        "type": "adobe",
        "adobeId": "foa1sjh",
    },
    234: {
        "fontName": "aotfudshinmarugopr6n",
        "fontNameJa": "A-OTF UD新丸ゴ Pr6N",
        "fontNameEn": "a-otf-ud-shin-maru-go-pr6n",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "bdl4kkz",
    },
    235: {
        "fontName": "abajiminchikuceb",
        "fontNameJa": "味明 築C/EB",
        "fontNameEn": "abajimin-chikuceb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mqv4bdy",
    },
    236: {
        "fontName": "murecho",
        "fontNameJa": "Murecho",
        "fontNameEn": "Murecho",
        "fontWeight": 900,
        "type": "google",
        "adobeId": "",
    },
    237: {
        "fontName": "shipporiantique",
        "fontNameJa": "しっぽりアンティーク",
        "fontNameEn": "Shippori Antique",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    238: {
        "fontName": "vdllineg",
        "fontNameJa": "VDL ラインＧ",
        "fontNameEn": "vdl-lineg",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "qgv6lvs",
    },
    240: {
        "fontName": "rondeb",
        "fontNameJa": "ロンド B スクエア",
        "fontNameEn": "ronde-b",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mcw3zep",
    },
    241: {
        "fontName": "shipporimincho",
        "fontNameJa": "しっぽり明朝",
        "fontNameEn": "Shippori Mincho",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    242: {
        "fontName": "mplus1",
        "fontNameJa": "Mplus 1",
        "fontNameEn": "M PLUS 1",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    243: {
        "fontName": "kiwimaru",
        "fontNameJa": "キウイ丸",
        "fontNameEn": "Kiwi Maru",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    244: {
        "fontName": "abkarutael",
        "fontNameJa": "AB-カルタEL",
        "fontNameEn": "ab-karuta-el",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "gft8anw",
    },
    245: {
        "fontName": "abkailight",
        "fontNameJa": "AB-楷 Light",
        "fontNameEn": "ab-kai-light",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "yjh1wau",
    },
    246: {
        "fontName": "abyamabikob",
        "fontNameJa": "AB-やまびこB",
        "fontNameEn": "ab-yamabiko-b",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "aiu1cal",
    },
    247: {
        "fontName": "abtyuusyobokunenn",
        "fontNameJa": "AB-忠書墨念",
        "fontNameEn": "ab-tyuusyobokunenn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "frs1dgw",
    },
    248: {
        "fontName": "kinutamaruminfujistdn",
        "fontNameJa": "砧 丸明Fuji StdN",
        "fontNameEn": "kinuta-maruminfuji-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "msp8whs",
    },
    249: {
        "fontName": "tbudgothicstd",
        "fontNameJa": "TBUDゴシック Std",
        "fontNameEn": "tbudgothic-std",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "naj3jlo",
    },
    250: {
        "fontName": "sawarabimincho",
        "fontNameJa": "さわらび明朝",
        "fontNameEn": "Sawarabi Mincho",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    251: {
        "fontName": "yuminchopr6n",
        "fontNameJa": "游明朝体 Pr6N",
        "fontNameEn": "yu-mincho-pr6n",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mcc3rel",
    },
    252: {
        "fontName": "heiseikakugothicstdn",
        "fontNameJa": "平成角ゴシック StdN",
        "fontNameEn": "heisei-kaku-gothic-stdn",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "kkk0fwe",
    },
    253: {
        "fontName": "mplus1",
        "fontNameJa": "Mplus 1",
        "fontNameEn": "M PLUS 1",
        "fontWeight": 600,
        "type": "google",
        "adobeId": "",
    },
    254: {
        "fontName": "abjarokubold",
        "fontNameJa": "AB-じゃろくB",
        "fontNameEn": "ab-jaroku-bold",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mor8mbr",
    },
    255: {
        "fontName": "zenkakugothicnew",
        "fontNameJa": "ZEN角ゴシック",
        "fontNameEn": "Zen Kaku Gothic New",
        "fontWeight": 900,
        "type": "google",
        "adobeId": "",
    },
    256: {
        "fontName": "iroha21popurastdn",
        "fontNameJa": "砧 iroha 21popura StdN",
        "fontNameEn": "iroha-21popura-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "odb7vbh",
    },
    257: {
        "fontName": "murecho",
        "fontNameJa": "Murecho",
        "fontNameEn": "Murecho",
        "fontWeight": 600,
        "type": "google",
        "adobeId": "",
    },
    258: {
        "fontName": "iroha31nirestdn",
        "fontNameJa": "砧 iroha 31nire StdN",
        "fontNameEn": "iroha-31nire-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "rts1igm",
    },
    259: {
        "fontName": "setofontsp",
        "fontNameJa": "瀬戸フォントSP",
        "fontNameEn": "setofont-sp",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "gnt1cmu",
    },
    260: {
        "fontName": "abikkyu",
        "fontNameJa": "AB-一丘",
        "fontNameEn": "ab-ikkyu",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "wpc5gyc",
    },
    261: {
        "fontName": "kleeone",
        "fontNameJa": "クレー One",
        "fontNameEn": "Klee One",
        "fontWeight": 600,
        "type": "google",
        "adobeId": "",
    },
    262: {
        "fontName": "mplus1",
        "fontNameJa": "Mplus 1",
        "fontNameEn": "M PLUS 1",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    263: {
        "fontName": "kurobaracinderella",
        "fontNameJa": "黒薔薇シンデレラ",
        "fontNameEn": "kurobara-cinderella",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "iyi1qwh",
    },
    264: {
        "fontName": "fotudkakugosmallpr6n",
        "fontNameJa": "FOT-UD角ゴ_スモール Pr6N",
        "fontNameEn": "fot-udkakugo-small-pr6n",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "irt7tpr",
    },
    265: {
        "fontName": "kosugimaru",
        "fontNameJa": "小杉丸フォント",
        "fontNameEn": "Kosugi Maru",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    266: {
        "fontName": "abyoshienoryokanm",
        "fontNameJa": "AB好恵の良寛さんM",
        "fontNameEn": "ab-yoshienoryokan-m",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ymr2alv",
    },
    267: {
        "fontName": "mplus1code",
        "fontNameJa": "Mplus 1 Code",
        "fontNameEn": "M PLUS 1 Code",
        "fontWeight": 200,
        "type": "google",
        "adobeId": "",
    },
    268: {
        "fontName": "rera",
        "fontNameJa": "レラ-２",
        "fontNameEn": "rera",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "vpd8lvx",
    },
    269: {
        "fontName": "mplus2",
        "fontNameJa": "Mplus 2",
        "fontNameEn": "M PLUS 2",
        "fontWeight": 200,
        "type": "google",
        "adobeId": "",
    },
    270: {
        "fontName": "taengeifude",
        "fontNameJa": "TA演芸筆",
        "fontNameEn": "ta-engeifude",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "zcy5uic",
    },
    271: {
        "fontName": "abkokorono3",
        "fontNameJa": "AB-こころNo.3",
        "fontNameEn": "ab-kokoro-no3",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mmm2fka",
    },
    272: {
        "fontName": "abtsurumaru",
        "fontNameJa": "ABつるまる",
        "fontNameEn": "ab-tsurumaru",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "whm4ifg",
    },
    273: {
        "fontName": "honokamarugothic",
        "fontNameJa": "ほのか丸ゴシック",
        "fontNameEn": "honoka-maru-gothic",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "nhk2krm",
    },
    274: {
        "fontName": "toppanbunkyumidashiminst",
        "fontNameJa": "凸版文久見出し明朝 Std",
        "fontNameEn": "toppan-bunkyu-midashi-min-st",
        "fontWeight": 900,
        "type": "adobe",
        "adobeId": "kew5zxg",
    },
    275: {
        "fontName": "takasanemarugo",
        "fontNameJa": "TA重ね丸ゴ",
        "fontNameEn": "ta-kasanemarugo",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "cms8gbj",
    },
    276: {
        "fontName": "dnpshueishogominchostd",
        "fontNameJa": "DNP 秀英初号明朝 Std",
        "fontNameEn": "dnp-shuei-shogomincho-std",
        "fontWeight": 700,
        "type": "adobe",
        "adobeId": "gzs6isw",
    },
    277: {
        "fontName": "hottenshokk",
        "fontNameJa": "HOT-白舟篆書教漢",
        "fontNameEn": "hot-tenshokk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mgz1bby",
    },
    278: {
        "fontName": "kaiseidecol",
        "fontNameJa": "解星デコール",
        "fontNameEn": "Kaisei Decol",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    279: {
        "fontName": "fottsukuaoldminpr6n",
        "fontNameJa": "FOT-筑紫Aオールド明朝 Pr6N",
        "fontNameEn": "fot-tsukuaoldmin-pr6n",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "guh2suj",
    },
    280: {
        "fontName": "nitalagorera",
        "fontNameJa": "ニタラゴレラ-３",
        "fontNameEn": "nitalago-rera",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "rlb0dqx",
    },
    282: {
        "fontName": "taf1blockline",
        "fontNameJa": "TA-F1ブロックライン",
        "fontNameEn": "ta-f1blockline",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "hrn6tyd",
    },
    283: {
        "fontName": "abkarutabold",
        "fontNameJa": "ABカルタBOLD",
        "fontNameEn": "ab-karuta-bold",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "yiw2ymc",
    },
    284: {
        "fontName": "vdllogona",
        "fontNameJa": "VDL ロゴナ",
        "fontNameEn": "vdl-logona",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "top6ppj",
    },
    285: {
        "fontName": "zenkakugothicnew",
        "fontNameJa": "ZEN角ゴシック",
        "fontNameEn": "Zen Kaku Gothic New",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    286: {
        "fontName": "dnpshueinminchostd",
        "fontNameJa": "DNP 秀英にじみ明朝 Std",
        "fontNameEn": "dnp-shuei-nmincho-std",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mya2ktf",
    },
    287: {
        "fontName": "murecho",
        "fontNameJa": "Murecho",
        "fontNameEn": "Murecho",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    288: {
        "fontName": "shipporimincho",
        "fontNameJa": "しっぽり明朝",
        "fontNameEn": "Shippori Mincho",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    289: {
        "fontName": "fotudmarugosmallpr6n",
        "fontNameJa": "FOT-UD丸ゴ_スモール Pr6N",
        "fontNameEn": "fot-udmarugo-small-pr6n",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "jaa5ijm",
    },
    290: {
        "fontName": "yujisyuku",
        "fontNameJa": "Yuji Syuku",
        "fontNameEn": "Yuji Syuku",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    291: {
        "fontName": "abpolcadot",
        "fontNameJa": "ABポルカドット",
        "fontNameEn": "ab-polcadot",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "jam2zgx",
    },
    292: {
        "fontName": "aotfgothicmb101pr6n",
        "fontNameJa": "ゴシックMB101",
        "fontNameEn": "a-otf-gothic-mb101-pr6n",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "qrt7kkt",
    },
    293: {
        "fontName": "abkokikaku",
        "fontNameJa": "AB Koki角",
        "fontNameEn": "ab-kokikaku",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "nui8jsh",
    },
    294: {
        "fontName": "takairegular",
        "fontNameJa": "TA-楷 Regular",
        "fontNameEn": "ta-kai-regular",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "uym3moq",
    },
    295: {
        "fontName": "zenoldmincho",
        "fontNameJa": "ZENオールド明朝",
        "fontNameEn": "Zen Old Mincho",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    296: {
        "fontName": "abajiminchikueb",
        "fontNameJa": "味明 築/EB",
        "fontNameEn": "abajimin-chikueb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ptb1qod",
    },
    297: {
        "fontName": "oradanominchogsrr",
        "fontNameJa": "Oradano Mincho GSRR",
        "fontNameEn": "oradano-mincho-gsrr",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "hoj0asm",
    },
    298: {
        "fontName": "toppanbunkyumidashigostd",
        "fontNameJa": "凸版文久見出しゴシック Std",
        "fontNameEn": "toppan-bunkyu-midashi-go-std",
        "fontWeight": 900,
        "type": "adobe",
        "adobeId": "fvl8wym",
    },
    299: {
        "fontName": "abtanteidan",
        "fontNameJa": "AB探偵団",
        "fontNameEn": "ab-tanteidan",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bec3agx",
    },
    300: {
        "fontName": "abmayuminwalk",
        "fontNameJa": "ABマユミンウォーク",
        "fontNameEn": "ab-mayuminwalk",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "sfp3fgm",
    },
    301: {
        "fontName": "abkesera",
        "fontNameJa": "ABケセラ",
        "fontNameEn": "ab-kesera",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tle7ijr",
    },
    302: {
        "fontName": "mplus1code",
        "fontNameJa": "Mplus 1 Code",
        "fontNameEn": "M PLUS 1 Code",
        "fontWeight": 300,
        "type": "google",
        "adobeId": "",
    },
    303: {
        "fontName": "vdlgigajr",
        "fontNameJa": "VDL ギガJr",
        "fontNameEn": "vdl-gigajr",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "tps2kvy",
    },
    304: {
        "fontName": "aotfudshingopr6n",
        "fontNameJa": "A-OTF UD新ゴ Pr6N",
        "fontNameEn": "a-otf-ud-shin-go-pr6n",
        "fontWeight": 300,
        "type": "adobe",
        "adobeId": "psg4qnc",
    },
    305: {
        "fontName": "abroman",
        "fontNameJa": "AB浪漫",
        "fontNameEn": "ab-roman",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "zxm6lln",
    },
    306: {
        "fontName": "shipporimincho",
        "fontNameJa": "しっぽり明朝",
        "fontNameEn": "Shippori Mincho",
        "fontWeight": 800,
        "type": "google",
        "adobeId": "",
    },
    308: {
        "fontName": "vdlkyosensya",
        "fontNameJa": "VDL 京千社",
        "fontNameEn": "vdl-kyosensya",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "dxx1muk",
    },
    309: {
        "fontName": "vdlkuromincho",
        "fontNameJa": "VDL 黒明朝",
        "fontNameEn": "vdl-kuromincho",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "wjr6cup",
    },
    310: {
        "fontName": "mplus2",
        "fontNameJa": "Mplus 2",
        "fontNameEn": "M PLUS 2",
        "fontWeight": 500,
        "type": "google",
        "adobeId": "",
    },
    311: {
        "fontName": "abajiminsyuveb",
        "fontNameJa": "味明 秀Ｖ/EB",
        "fontNameEn": "abajimin-syuveb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "fit7zvh",
    },
    312: {
        "fontName": "fotudkakugoc80pro",
        "fontNameJa": "FOT-UD角ゴC80 Pro",
        "fontNameEn": "fot-udkakugoc80-pro",
        "fontWeight": 700,
        "type": "adobe",
        "adobeId": "oyn1iin",
    },
    313: {
        "fontName": "shinryu",
        "fontNameJa": "心龍爽",
        "fontNameEn": "shinryu",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bnp7rpb",
    },
    314: {
        "fontName": "vdlgigamarujr",
        "fontNameJa": "VDL ギガ丸Jr",
        "fontNameEn": "vdl-gigamarujr",
        "fontWeight": 500,
        "type": "adobe",
        "adobeId": "gjd0dgy",
    },
    315: {
        "fontName": "yugothicpr6n",
        "fontNameJa": "游ゴシック体",
        "fontNameEn": "yu-gothic-pr6n",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mea1ajs",
    },
    316: {
        "fontName": "abajiminmineb",
        "fontNameJa": "味明 民/EB",
        "fontNameEn": "abajimin-mineb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ate8dru",
    },
    317: {
        "fontName": "abplus",
        "fontNameJa": "ABプラス",
        "fontNameEn": "ab-plus",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ley2ftp",
    },
    318: {
        "fontName": "notoserifjp",
        "fontNameJa": "Noto Serif Japanese",
        "fontNameEn": "Noto Serif Japanese",
        "fontWeight": 900,
        "type": "google",
        "adobeId": "",
    },
    319: {
        "fontName": "abjchoki",
        "fontNameJa": "ABＪチョキ",
        "fontNameEn": "ab-j-choki",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "vtq0dgt",
    },
    320: {
        "fontName": "abootori",
        "fontNameJa": "AB 鳳",
        "fontNameEn": "ab-ootori",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "pex4qth",
    },
    321: {
        "fontName": "tashizuku",
        "fontNameJa": "TA-雫",
        "fontNameEn": "ta-shizuku",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mjo1nax",
    },
    322: {
        "fontName": "abhouganm500",
        "fontNameJa": "AB-方眼Ｍ500",
        "fontNameEn": "ab-hougan-m500",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "gcj8mbb",
    },
    323: {
        "fontName": "abkazunaunf",
        "fontNameJa": "AB-カズン阿吽F",
        "fontNameEn": "ab-kazunaun-f",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "kgv2wdz",
    },
    324: {
        "fontName": "vdlpenlady",
        "fontNameJa": "VDL ペンレディ",
        "fontNameEn": "vdl-penlady",
        "fontWeight": 700,
        "type": "adobe",
        "adobeId": "mrm8cua",
    },
    325: {
        "fontName": "abtsubaki",
        "fontNameJa": "AB-椿",
        "fontNameEn": "ab-tsubaki",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bpw4qpa",
    },
    326: {
        "fontName": "murecho",
        "fontNameJa": "Murecho",
        "fontNameEn": "Murecho",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    327: {
        "fontName": "yamamotoanclassicstdn",
        "fontNameJa": "砧 山本庵クラシック StdN",
        "fontNameEn": "yamamotoan-classic-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "spc2lnx",
    },
    328: {
        "fontName": "abtsurara",
        "fontNameJa": "AB-つらら",
        "fontNameEn": "ab-tsurara",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "wnb8pkr",
    },
    329: {
        "fontName": "murecho",
        "fontNameJa": "Murecho",
        "fontNameEn": "Murecho",
        "fontWeight": 100,
        "type": "google",
        "adobeId": "",
    },
    330: {
        "fontName": "zenkurenaido",
        "fontNameJa": "ZEN紅道",
        "fontNameEn": "Zen Kurenaido",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    331: {
        "fontName": "abhiro",
        "fontNameJa": "AB-ひろ",
        "fontNameEn": "ab-hiro",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "zdr2xyb",
    },
    332: {
        "fontName": "kinutamaruminshinanostdn",
        "fontNameJa": "砧 丸明Shinano StdN",
        "fontNameEn": "kinuta-maruminshinano-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "icq2zai",
    },
    333: {
        "fontName": "abkirigirisu",
        "fontNameJa": "ABキリギリス",
        "fontNameEn": "ab-kirigirisu",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ykt7iid",
    },
    334: {
        "fontName": "sawarabigothic",
        "fontNameJa": "さわらびゴシック",
        "fontNameEn": "Sawarabi Gothic",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    335: {
        "fontName": "zenoldmincho",
        "fontNameJa": "ZENオールド明朝",
        "fontNameEn": "Zen Old Mincho",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    336: {
        "fontName": "abyogurt",
        "fontNameJa": "AB-ヨーグルト",
        "fontNameEn": "ab-yogurt",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "azn7wph",
    },
    337: {
        "fontName": "abyoshienoryokanb",
        "fontNameJa": "AB好恵の良寛さんB",
        "fontNameEn": "ab-yoshienoryokan-b",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "fsx6ckx",
    },
    338: {
        "fontName": "abajiminmsoeb",
        "fontNameJa": "味明 Modern 草/EB",
        "fontNameEn": "abajiminm-soeb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "jud0mqv",
    },
    339: {
        "fontName": "kaiseiharunoumi",
        "fontNameJa": "解星 春の海",
        "fontNameEn": "Kaisei HarunoUmi",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    340: {
        "fontName": "notoserifjp",
        "fontNameJa": "Noto Serif Japanese",
        "fontNameEn": "Noto Serif Japanese",
        "fontWeight": 200,
        "type": "google",
        "adobeId": "",
    },
    341: {
        "fontName": "abcircle",
        "fontNameJa": "AB-サークル",
        "fontNameEn": "ab-circle",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "art7xyn",
    },
    342: {
        "fontName": "abneuron",
        "fontNameJa": "ABニューロン",
        "fontNameEn": "ab-neuron",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tjg4flx",
    },
    343: {
        "fontName": "abjgu",
        "fontNameJa": "ABＪグー",
        "fontNameEn": "ab-j-gu",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "pyw3heq",
    },
    344: {
        "fontName": "absanpobito",
        "fontNameJa": "AB散歩人",
        "fontNameEn": "ab-sanpobito",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "zij3xpb",
    },
    345: {
        "fontName": "abajiminmgyoeb",
        "fontNameJa": "味明 Modern 行/EB",
        "fontNameEn": "abajiminm-gyoeb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "bfu5ayh",
    },
    346: {
        "fontName": "iroha23kaedestdn",
        "fontNameJa": "砧 iroha 23kaede StdN",
        "fontNameEn": "iroha-23kaede-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tow5upu",
    },
    347: {
        "fontName": "abkotsubu",
        "fontNameJa": "AB小粒",
        "fontNameEn": "ab-kotsubu",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "wvb3qei",
    },
    348: {
        "fontName": "kinutamaruminoldstdn",
        "fontNameJa": "砧 丸明オールド StdN",
        "fontNameEn": "kinuta-maruminold-stdn",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "uqv2uzj",
    },
    349: {
        "fontName": "rocknrollone",
        "fontNameJa": "ロックンロール One",
        "fontNameEn": "RocknRoll One",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    350: {
        "fontName": "notosansjp",
        "fontNameJa": "Noto Sans Japanese",
        "fontNameEn": "Noto Sans Japanese",
        "fontWeight": 900,
        "type": "google",
        "adobeId": "",
    },
    351: {
        "fontName": "tarehitsum",
        "fontNameJa": "TA-礼筆M",
        "fontNameEn": "ta-rehitsu-m",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "zhq7osp",
    },
    352: {
        "fontName": "fotudminchopr6n",
        "fontNameJa": "FOT-UD明朝 Pr6N",
        "fontNameEn": "fot-udmincho-pr6n",
        "fontWeight": 700,
        "type": "adobe",
        "adobeId": "wit5lza",
    },
    353: {
        "fontName": "abajiminmsyuleb",
        "fontNameJa": "味明 Modern 秀L/EB",
        "fontNameEn": "abajiminm-syuleb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "nfr8cjk",
    },
    354: {
        "fontName": "abajiminmkoheb",
        "fontNameJa": "味明 Modern 弘/EB",
        "fontNameEn": "abajiminm-koheb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "tza6clo",
    },
    355: {
        "fontName": "happyruika",
        "fontNameJa": "ハッピールイカ-０５",
        "fontNameEn": "happy-ruika",
        "fontWeight": 100,
        "type": "adobe",
        "adobeId": "rxq3mge",
    },
    357: {
        "fontName": "hachimarupop",
        "fontNameJa": "はちまるポップ",
        "fontNameEn": "Hachi Maru Pop",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    358: {
        "fontName": "abcountryroad",
        "fontNameJa": "ABカントリーロード",
        "fontNameEn": "ab-countryroad",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "ryw0jxf",
    },
    359: {
        "fontName": "zenkakugothicantique",
        "fontNameJa": "ZEN角ゴシックアンティーク",
        "fontNameEn": "Zen Kaku Gothic Antique",
        "fontWeight": 900,
        "type": "google",
        "adobeId": "",
    },
    360: {
        "fontName": "zenantiquesoft",
        "fontNameJa": "ZENアンチックソフト",
        "fontNameEn": "Zen Antique Soft",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    361: {
        "fontName": "abshiguma",
        "fontNameJa": "ABシグマ",
        "fontNameEn": "ab-shiguma",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "xsy7xrl",
    },
    362: {
        "fontName": "mplus1",
        "fontNameJa": "Mplus 1",
        "fontNameEn": "M PLUS 1",
        "fontWeight": 200,
        "type": "google",
        "adobeId": "",
    },
    363: {
        "fontName": "abseiryulight",
        "fontNameJa": "AB-青龍L",
        "fontNameEn": "ab-seiryu-light",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "mud8bax",
    },
    364: {
        "fontName": "abajiminmryoeb",
        "fontNameJa": "味明 Modern 良/EB",
        "fontNameEn": "abajiminm-ryoeb",
        "fontWeight": 400,
        "type": "adobe",
        "adobeId": "wqb3jtr",
    },
    239: {
        "fontName": "morisawabizudgothic",
        "fontNameJa": "モリサワBIZ UDゴシック",
        "fontNameEn": "BIZ UDGothic",
        "fontWeight": 700,
        "type": "google",
        "adobeId": "",
    },
    356: {
        "fontName": "morisawabizudgothic",
        "fontNameJa": "モリサワBIZ UDゴシック",
        "fontNameEn": "BIZ UDGothic",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    281: {
        "fontName": "morisawabizudmincho",
        "fontNameJa": "モリサワBIZ UD明朝",
        "fontNameEn": "BIZ UDMincho",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
    307: {
        "fontName": "morisawabizudpmincho",
        "fontNameJa": "モリサワBIZ UDP明朝",
        "fontNameEn": "BIZ UDPMincho",
        "fontWeight": 400,
        "type": "google",
        "adobeId": "",
    },
}
320
