name: push-image

on:
  workflow_run:
    workflows:
      - test
    branches: [main]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-1"

      - name: Install AWS Cli v2
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2

      - name: Install lightsailctl Plugin
        run: |
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: Build, tag, and push image to Lightsail container
        run: |
          IMAGE_TAG=$(echo v$(date +"%Y%m%d_%H%M"))
          docker build -t font-search-api:$IMAGE_TAG .
          aws lightsail push-container-image --region ap-northeast-1 --service-name fontpint --label font-search-api --image font-search-api:$IMAGE_TAG
